<a href="https://colab.research.google.com/github/Abhishekauti21/dsmp-pre-work/blob/master/Numpy_pract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#find a non singular matrix

In [1]:
import numpy as np
# initialize array B and Identity matrix
B = np.array([[2,0,-1], [0,2,-1], [-1,0,1]])
I = np.identity(3)

# calculate result
A = 3*I - B
print(A)

[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 2.]]


In [0]:
#Solving System of Equations with NumPy

In [2]:
import numpy as np
# initialize matrix A and b
A = np.array([[2,1,2], [3,0,1], [1,1,-1]])
b=np.array([-3,5,2])
# Solve for x
x=np.linalg.solve(A,b)

# Check solution
check=np.allclose(np.dot(A,x),b)
print(check)

True


In [3]:
a = np.array([[0, 1, 2], [3, 4, 5]])
b = a.sum(axis=1)
print (b)


[ 3 12]


In [4]:
import numpy as np

a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c*a

print (c[2])


21


In [6]:
import numpy as np

a = np.zeros(6)
b = np.arange(0,10,2)
c = a + b
print (c[4])


ValueError: ignored

In [7]:
a = np.array([[0, 1, 0], [1, 0, 1]])
a += 3
b = a + 3
print (a[1,2] + b[1,2])

11


In [8]:
import numpy as np

a = np.array([[0, 1, 2], [3, 4, 5]])
b = a.sum(axis=1)
print (b)


[ 3 12]


In [9]:
import numpy as np

a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c
print(d[1,2])


5


In [10]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.arange(0,10,2)
c = a + b
print (c[4])


13


In [13]:
import numpy as np
# Code starts here

# initialize NumPy array
array=np.arange(1, 11)

# check dimensions
dim=array.ndim
print(dim)
# reshaped array
reshaped=array.reshape(5,2)

# check shape
new_dim=reshaped.ndim
print(new_dim)
# Code ends here

1
2


In [14]:
import numpy as np
array=np.eye(4,dtype="float32")
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
import numpy as np

# Code starts here

# marks array
marks = np.array([20, 30, 40])
# ID array
ids = np.linspace(0,4,3)

# display marks and id array
print(marks,ids)

# Code ends here

[20 30 40] [0. 2. 4.]


In [16]:
# Code starts here
import numpy as np
# initialize array
array = np.array([3, 4.5, 3+5j, 0])

# boolean filter
real = np.isreal(array)
real_array = array[real]
print(real_array)


# boolean filter
imag = np.iscomplex(array)
imag_array = array[imag]
print(imag_array)
# Code ends here

[3. +0.j 4.5+0.j 0. +0.j]
[3.+5.j]


In [17]:
import numpy as np
# initialize array for prices
prices=np.array([[40, 35, 20], [21, 48, 70]])

# Code starts here

# flatten the array
prices=prices.flatten()

# minimum price
buying_price=np.min(prices)

# index of buying price
index = list(prices).index(buying_price)

# create subset
new_prices = prices[index:]

# selling price
selling_price = np.max(new_prices)

# profit
profit = selling_price - buying_price
# display
print(prices)
print(buying_price)
print(index)
print(new_prices)
print(selling_price)
print(profit)
# Code ends here

[40 35 20 21 48 70]
20
2
[20 21 48 70]
70
50


In [18]:
import numpy as np
np.random.seed(21)

# Code starts here

# create random 5x5 array
z=np.random.random((5,5))
# minimum and maximum values
zmax=z.max()
zmin=z.min()
# normalize
z_norm=np.divide(z-zmin,zmax-zmin)
# display
print(z_norm)

[[0.02856942 0.28190767 0.73703555 0.         0.19423813]
 [0.03072817 0.29577917 0.67690496 0.3019365  0.59225784]
 [0.05053881 0.89136471 0.1176393  0.16494209 0.49987233]
 [0.88746023 0.77705951 1.         0.77743756 0.38217481]
 [0.40796162 0.72901978 0.26247412 0.87734633 0.93959001]]


In [19]:
# import packages
import numpy as np

# Code starts here

# co-efficients of x
coeff=np.array([1,-4,4])

# roots of equation
roots=np.roots(coeff)

# display roots
print(roots)

# Code ends here

[2. 2.]


In [20]:
# Code starts here
import numpy as np
# centigrade temperatures
centigrade_temps = np.array([0, 10, 25, 32, 80, 99.99])

# function for conversion
def convert(celsius):
    return 1.8*celsius + 32
fahrenheit_temps = convert(centigrade_temps)
# display fahrehheit temperatures
print(fahrenheit_temps)

# Code ends here

[ 32.     50.     77.     89.6   176.    211.982]


In [21]:
# Code starts here
import numpy as np
# initialize matrix A and b
A = np.array([[2,1,2], [3,0,1], [1,1,-1]])
b=np.array([-3,5,2])
# Solve for x
x=np.linalg.solve(A,b)

# Check solution
check=np.allclose(np.dot(A,x),b)
print(check)
# Code ends here

True


In [22]:
import numpy as np
# initialize array B and Identity matrix
B = np.array([[2,0,-1], [0,2,-1], [-1,0,1]])
I = np.identity(3)

# calculate result
A = 3*I - B
print(A)

# Code ends here

[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 2.]]
